-- ===============================
-- DROP in dependency-safe order
-- ===============================
DROP TRIGGER IF EXISTS "set_expires_at" ON "sessions";
DROP FUNCTION IF EXISTS set_expires_at();
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "expenses" CASCADE;
DROP TABLE IF EXISTS "income" CASCADE;
DROP TABLE IF EXISTS "user_account" CASCADE;

-- ===============================
-- user_account
-- ===============================
CREATE TABLE IF NOT EXISTS "user_account" (
  "accountId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" CHAR(20) NOT NULL,
  "lastName"  CHAR(20) NOT NULL,
  "username"  CHAR(20) UNIQUE NOT NULL,
  "birthday"  DATE NOT NULL,
  "currency"  CHAR(10) NOT NULL,
  "password"  VARCHAR(100) NOT NULL,
  "email"     CHAR(50) UNIQUE NOT NULL,
  "system_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===============================
-- income
-- ===============================
CREATE TABLE IF NOT EXISTS "income" (
  "accountId" INT NOT NULL,
  "transactionId" CHAR(36) PRIMARY KEY,
  "type" CHAR(10) NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "source" CHAR(50) NOT NULL,
  "description" VARCHAR(100) NOT NULL,
  "date" DATE NOT NULL,
  "system_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "income_accountId_fkey"
    FOREIGN KEY ("accountId")
    REFERENCES "user_account"("accountId")
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- ===============================
-- expenses
-- ===============================
CREATE TABLE IF NOT EXISTS "expenses" (
  "accountId" INT NOT NULL,
  "transactionId" CHAR(36) PRIMARY KEY,
  "type" CHAR(10) NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "category" CHAR(50) NOT NULL,
  "description" VARCHAR(100) NOT NULL,
  "date" DATE NOT NULL,
  "system_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "expenses_accountId_fkey"
    FOREIGN KEY ("accountId")
    REFERENCES "user_account"("accountId")
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- ===============================
-- sessions
-- ===============================
CREATE TABLE IF NOT EXISTS "sessions" (
  "sessionId" CHAR(36) PRIMARY KEY,
  "accountId" INT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" TIMESTAMPTZ,
  CONSTRAINT "sessions_accountId_fkey"
    FOREIGN KEY ("accountId")
    REFERENCES "user_account"("accountId")
);

-- ===============================
-- Trigger: set_expires_at (PG version)
-- ===============================
CREATE OR REPLACE FUNCTION set_expires_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."expires_at" IS NULL THEN
    NEW."expires_at" := NEW."created_at" + INTERVAL '24 hours';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "set_expires_at" ON "sessions";
CREATE TRIGGER "set_expires_at"
BEFORE INSERT ON "sessions"
FOR EACH ROW
EXECUTE FUNCTION set_expires_at();

-- ===============================
-- Sample selects (note the quotes)
-- ===============================
SELECT * FROM "user_account";
SELECT * FROM "income";
SELECT * FROM "expenses";
SELECT * FROM "sessions";
